// GENERATED by scripts/sync-shopify.mjs on 2026-09-29T07:52:56.681Z — do not edit by hand.
// The biolane.ph listings the site falls back to when the store can't be
// reached, and the ones the tests run against. Run `npm run sync-shopify`
// to refresh it.
import type { CatalogSnapshot } from '../lib/shopify-catalog.ts'

export const shopifySnapshot: CatalogSnapshot = {
  "fetchedAt": "2026-09-29T07:52:56.681Z",
  "listings": {
    "cleanser-2in1-200": {
      "title": "Biolane Baby Body & Hair Cleanser — 200 ml",
      "handle": "biolane-baby-body-hair-wash-gel-copy-copy",
      "variantId": 42497723662402,
      "price": 544,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Biolane_2in1_Body_and_Hair_Cleanser_200ml_11d6be73-d5d7-46ba-bd78-5561152f4098.jpg?v=1759827395",
      "url": "https://biolane.ph/products/biolane-baby-body-hair-wash-gel-copy-copy?variant=42497723662402"
    },
    "cleanser-2in1-350": {
      "title": "Biolane Baby Body & Hair Cleanser — 350 ml",
      "handle": "biolane-baby-body-hair-wash-gel-copy-copy",
      "variantId": 42497723695170,
      "price": 688,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Biolane_2in1_Body_and_Hair_Cleanser_350ml.jpg?v=1744703146",
      "url": "https://biolane.ph/products/biolane-baby-body-hair-wash-gel-copy-copy?variant=42497723695170"
    },
    "cleanser-2in1-750": {
      "title": "Biolane Baby Body & Hair Cleanser — 750 ml",
      "handle": "biolane-baby-body-hair-wash-gel-copy-copy",
      "variantId": 42497723760706,
      "price": 1078,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Biolane_2in1_Body_and_Hair_Cleanser_750ml.jpg?v=1743058776",
      "url": "https://biolane.ph/products/biolane-baby-body-hair-wash-gel-copy-copy?variant=42497723760706"
    },
    "gentle-shampoo-200": {
      "title": "Biolane Gentle Shampoo 350 ml — Biolane Gentle Shampoo 200ml",
      "handle": "biolane-gentle-shampoo-copy",
      "variantId": 45251587833922,
      "price": 440,
      "compareAt": 676,
      "available": false,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Gentle_Shampoo_200ml_9f284a44-a45f-473c-8ff4-ab601efa7249.png?v=1789973104",
      "url": "https://biolane.ph/products/biolane-gentle-shampoo-copy?variant=45251587833922"
    },
    "gentle-shampoo-350": {
      "title": "Biolane Gentle Shampoo 350 ml — Biolane Gentle Shampoo 350ml",
      "handle": "biolane-gentle-shampoo-copy",
      "variantId": 42496835223618,
      "price": 575,
      "compareAt": 676,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Gentle_Shampoo_with_Flax_350ml.png?v=1789970385",
      "url": "https://biolane.ph/products/biolane-gentle-shampoo-copy?variant=42496835223618"
    },
    "pure-h2o-350": {
      "title": "Biolane Pure H2O Cleanser 350 ml — Biolane Pure H2o 350ml",
      "handle": "biolane-pure-h2o-cleanser-copy-1",
      "variantId": 45132200607810,
      "price": 915,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Pure_H2O_350ml_8a1236cc-6911-4cd5-8b1f-fce4b4364e86.png?v=1785130483",
      "url": "https://biolane.ph/products/biolane-pure-h2o-cleanser-copy-1?variant=45132200607810"
    },
    "pure-h2o-750": {
      "title": "Biolane Pure H2O Cleanser 750 ml",
      "handle": "pure-h2o",
      "variantId": 42101717368898,
      "price": 915,
      "compareAt": 1078,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Pure_H2O_750ml.png?v=1785130565",
      "url": "https://biolane.ph/products/pure-h2o"
    },
    "pure-h2o-400-refill": {
      "title": "Biolane Pure H2O Cleanser 350 ml — Biolane Pure H2o Refill",
      "handle": "biolane-pure-h2o-cleanser-copy-1",
      "variantId": 45154094547010,
      "price": 595,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Pure_H2O_Refill.png?v=1788521195",
      "url": "https://biolane.ph/products/biolane-pure-h2o-cleanser-copy-1?variant=45154094547010"
    },
    "cleansing-milk-750": {
      "title": "Biolane Gentle Cleansing Milk",
      "handle": "biolane-gentle-cleansing-milk-for-baby-face-body-diaper-area-750ml",
      "variantId": 42101705015362,
      "price": 1075,
      "compareAt": 1265,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Cleansing_Milk_350ml.png?v=1785130366",
      "url": "https://biolane.ph/products/biolane-gentle-cleansing-milk-for-baby-face-body-diaper-area-750ml"
    },
    "rich-soap-150": {
      "title": "Biolane Extra Rich Soap for Baby",
      "handle": "biolane-extra-rich-soap-for-baby-150g",
      "variantId": 42101706129474,
      "price": 323,
      "compareAt": 380,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Extra_Rich_Soap.png?v=1785130185",
      "url": "https://biolane.ph/products/biolane-extra-rich-soap-for-baby-150g"
    },
    "cradle-cap-shampoo-150": {
      "title": "Biolane Cradle Cap  Shampoo 150ml",
      "handle": "biolane-cradle-cap-shampoo-150ml",
      "variantId": 42472618852418,
      "price": 580,
      "compareAt": 682,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/CradleCap.jpg?v=1758779634",
      "url": "https://biolane.ph/products/biolane-cradle-cap-shampoo-150ml"
    },
    "diaper-change-cream-100": {
      "title": "Biolane Diaper Changing Cream 100 ml",
      "handle": "diaper-change-cream",
      "variantId": 42048778666050,
      "price": 545,
      "compareAt": 638,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Diaper_Cream_100ml.png?v=1785132014",
      "url": "https://biolane.ph/products/diaper-change-cream"
    },
    "cleansing-milk-wipes-72": {
      "title": "Biolane Baby Milk Cleansing Wipes 72 Sheets | Wet Wipes for Newborn & Sensitive Skin | Moisturizing",
      "handle": "biolane-baby-milk-cleansing-wipes-72-sheets-wet-wipes-for-newborn-sensitive-skin-moisturizing",
      "variantId": 43893596717122,
      "price": 493,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Milk_Wipes.png?v=1785130425",
      "url": "https://biolane.ph/products/biolane-baby-milk-cleansing-wipes-72-sheets-wet-wipes-for-newborn-sensitive-skin-moisturizing"
    },
    "body-milk-350": {
      "title": "Biolane Moisturizing Body Milk 350ml",
      "handle": "biolane-moisturizing-body-milk-350ml",
      "variantId": 42101849915458,
      "price": 835,
      "compareAt": 979,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Body_Milk_350ml.png?v=1785131458",
      "url": "https://biolane.ph/products/biolane-moisturizing-body-milk-350ml"
    },
    "nourishing-cream-100": {
      "title": "Biolane Organic Nourishing & Moisturizing Cream 100 ml",
      "handle": "nourishing-and-moisturizing-cream",
      "variantId": 41979185037378,
      "price": 550,
      "compareAt": 649,
      "available": false,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Nourishing_Cream_200ml.png?v=1785131797",
      "url": "https://biolane.ph/products/nourishing-and-moisturizing-cream"
    },
    "almond-oil-spray-75": {
      "title": "Biolane Sweet Almond Oil Spray",
      "handle": "biolane-sweet-almond-oil-spray-75ml",
      "variantId": 42101774450754,
      "price": 485,
      "compareAt": 572,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/BHA75EXP_HUILEAMANDEDOUCE.jpg?v=1744704646",
      "url": "https://biolane.ph/products/biolane-sweet-almond-oil-spray-75ml"
    },
    "skin-fragrance": {
      "title": "Biolane Skin Freshening Fragrance",
      "handle": "biolane-baby-skin-freshening-mist-200ml-gentle-citrus-floral-scent-alcohol-free",
      "variantId": 42078474338370,
      "price": 463,
      "compareAt": 545,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Skin_Fragrance.png?v=1785130981",
      "url": "https://biolane.ph/products/biolane-baby-skin-freshening-mist-200ml-gentle-citrus-floral-scent-alcohol-free"
    },
    "liquid-powder-100": {
      "title": "Biolane Liquid Talc",
      "handle": "biolane-liquid-talc-100ml-hypoallergenic-non-powder-formula-for-baby-s-delicate-skin",
      "variantId": 42078529749058,
      "price": 795,
      "compareAt": 935,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Liquid_Talc_100ml_ce9b93d5-0e2f-4bab-ad0d-d5e480629cce.png?v=1785132097",
      "url": "https://biolane.ph/products/biolane-liquid-talc-100ml-hypoallergenic-non-powder-formula-for-baby-s-delicate-skin"
    },
    "styling-gel-100": {
      "title": "Biolane Styling Hair Gel",
      "handle": "biolane-styling-hair-gel-100ml",
      "variantId": 42103270244418,
      "price": 495,
      "compareAt": 545,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Styling_Gel.png?v=1785131106",
      "url": "https://biolane.ph/products/biolane-styling-hair-gel-100ml"
    },
    "cicabebe-3in1-40": {
      "title": "Biolane Cicabébé Ointment",
      "handle": "biolane-cicabebe-ointment-40ml-3-in-1-soothing-healing-balm-for-baby-s-sensitive-skin",
      "variantId": 42078553145410,
      "price": 635,
      "compareAt": 748,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Cicabebe.png?v=1785131561",
      "url": "https://biolane.ph/products/biolane-cicabebe-ointment-40ml-3-in-1-soothing-healing-balm-for-baby-s-sensitive-skin"
    },
    "arnica-gel-20": {
      "title": "Biolane Organic Arnica Gel",
      "handle": "biolane-organic-arnica-gel-20ml",
      "variantId": 42101786837058,
      "price": 465,
      "compareAt": 545,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/BBGA20_GELARNICA.jpg?v=1744705628",
      "url": "https://biolane.ph/products/biolane-organic-arnica-gel-20ml"
    },
    "topilane-cleansing-cream-350": {
      "title": "Biolane Topilane AD Soothing Cleansing Cream",
      "handle": "biolane-topilane-ad-soothing-cleansing-cream-for-dry-to-atopic-prone-baby-skin-350ml",
      "variantId": 42101793423426,
      "price": 980,
      "compareAt": 1155,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Topilane_Soothing_Cream.png?v=1785284219",
      "url": "https://biolane.ph/products/biolane-topilane-ad-soothing-cleansing-cream-for-dry-to-atopic-prone-baby-skin-350ml"
    },
    "topilane-cleansing-oil-350": {
      "title": "Biolane Topilane AD Protective Cleansing Oil",
      "handle": "biolane-topilane-ad-protective-cleansing-oil-350ml",
      "variantId": 42101791064130,
      "price": 980,
      "compareAt": 1155,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Topilane_Cleansing_Oil.png?v=1785284220",
      "url": "https://biolane.ph/products/biolane-topilane-ad-protective-cleansing-oil-350ml"
    },
    "topilane-body-balm-350": {
      "title": "Biolane Topilane AD Lipid-Replenishing Body Balm",
      "handle": "biolane-topilane-ad-lipid-replenishing-body-balm-for-dry-to-atopic-prone-baby-skin-350ml",
      "variantId": 42101797388354,
      "price": 1115,
      "compareAt": 1309,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Topilane_Lipid_Body_Balm.png?v=1785284220",
      "url": "https://biolane.ph/products/biolane-topilane-ad-lipid-replenishing-body-balm-for-dry-to-atopic-prone-baby-skin-350ml"
    },
    "topilane-face-cream-50": {
      "title": "Biolane Topilane AD Emollient Face Cream for Babies",
      "handle": "biolane-topilane-ad-emollient-face-cream-for-babies-50ml",
      "variantId": 42101803745346,
      "price": 590,
      "compareAt": 649,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Topilane_Face_Cream.png?v=1785284220",
      "url": "https://biolane.ph/products/biolane-topilane-ad-emollient-face-cream-for-babies-50ml"
    },
    "sunstick": {
      "title": "Biolane Baby Sunstick SPF 50+",
      "handle": "biolane-baby-sunstick-spf-50",
      "variantId": 42474740154434,
      "price": 830,
      "compareAt": 925,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Sun_Stick.png?v=1785132317",
      "url": "https://biolane.ph/products/biolane-baby-sunstick-spf-50"
    },
    "suncream": {
      "title": "Biolane Sun Cream",
      "handle": "biolane-sun-cream",
      "variantId": 44544760119362,
      "price": 895,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/SunCream.png?v=1785309687",
      "url": "https://biolane.ph/products/biolane-sun-cream"
    },
    "sunspray": {
      "title": "Biolane Sun Spray",
      "handle": "biolane-sun-spray",
      "variantId": 44544760086594,
      "price": 1850.2,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/SunSpray_57c1dfa8-3307-4979-9d58-1e97260b2005.png?v=1785310096",
      "url": "https://biolane.ph/products/biolane-sun-spray"
    },
    "mosquito-stick": {
      "title": "Biolane Expert Baby Mosquito Stick",
      "handle": "biolane-expert-baby-mosquito-stick",
      "variantId": 45154095726658,
      "price": 656,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Mosquito_Stick.png?v=1788521203",
      "url": "https://biolane.ph/products/biolane-expert-baby-mosquito-stick"
    },
    "stretch-marks-cream-200": {
      "title": "Biolane Stretchmark Cream",
      "handle": "stretch-marks-cream",
      "variantId": 41979179008066,
      "price": 925,
      "compareAt": 1089,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Stretch_Marks_Cream_6716f1ca-0f38-47e2-b5dd-54ecd56763bc.png?v=1785132235",
      "url": "https://biolane.ph/products/stretch-marks-cream"
    },
    "nursing-balm-40": {
      "title": "Biolane Soothing Repairing Balm",
      "handle": "biolane-soothing-repairing-balm-40ml",
      "variantId": 42103269523522,
      "price": 675,
      "compareAt": 792,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/Nursing_Balm_40ml.jpg?v=1745997855",
      "url": "https://biolane.ph/products/biolane-soothing-repairing-balm-40ml"
    },
    "intimate-hygiene-gel": {
      "title": "Feminine Wash",
      "handle": "feminine-wash",
      "variantId": 44706574008386,
      "price": 772.8,
      "compareAt": null,
      "available": true,
      "image": "https://cdn.shopify.com/s/files/1/0606/5183/1362/files/FeminineWash.png?v=1786340437",
      "url": "https://biolane.ph/products/feminine-wash"
    }
  }
}
