/**
 * Re-reads the biolane.ph catalogue and rewrites data/shopify-snapshot.ts,
 * the copy the site falls back to when the store can't be reached (and the
 * copy the tests run against). Prints an audit of every product.
 *
 *     npm run sync-shopify            fetch from biolane.ph
 *     node scripts/sync-shopify.mjs path/to/products.json   use a saved copy
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { SHOP_PRODUCTS_URL, matchListings } from '../lib/shopify-catalog.ts'
import { shopifyMap } from '../data/shopify-map.ts'
import { productDefs } from '../data/products.ts'

const OUT = new URL('../data/shopify-snapshot.ts', import.meta.url)

let previous = {}
try {
  const mod = await import(OUT.href)
  previous = mod.shopifySnapshot.listings
} catch {
  /* first run */
}

let shop
if (process.argv[2]) {
  shop = JSON.parse(readFileSync(process.argv[2], 'utf8')).products
} else {
  const res = await fetch(SHOP_PRODUCTS_URL, { signal: AbortSignal.timeout(20000) })
  if (!res.ok) {
    console.error(`biolane.ph answered ${res.status}; snapshot left unchanged.`)
    process.exit(1)
  }
  shop = (await res.json()).products
}
if (!Array.isArray(shop) || shop.length === 0) {
  console.error('No products in the store answer; snapshot left unchanged.')
  process.exit(1)
}

const { listings, missing } = matchListings(shop, shopifyMap)
const fetchedAt = new Date().toISOString()

const unmapped = productDefs.filter((d) => !(d.id in shopifyMap)).map((d) => d.id)
const strayMap = Object.keys(shopifyMap).filter((id) => !productDefs.some((d) => d.id === id))

console.log(`\nbiolane.ph: ${shop.length} listings. Matched ${Object.keys(listings).length} of ${Object.keys(shopifyMap).length} mapped products.\n`)
const peso = (n) => (n === null || n === undefined ? '—' : '₱' + n.toLocaleString('en-PH', { minimumFractionDigits: n % 1 ? 2 : 0 }))
for (const def of productDefs) {
  const l = listings[def.id]
  const was = previous[def.id]
  const label = `${def.name}${def.size ? ' ' + def.size : ''}`.padEnd(44)
  if (!l) {
    console.log(`  ${label} NOT ON biolane.ph${def.note ? '  (' + def.note + ')' : ''}`)
    continue
  }
  const flags = []
  if (!l.available) flags.push('SOLD OUT')
  if (was && was.price !== l.price) flags.push(`price was ${peso(was.price)}`)
  if (was && was.available !== l.available) flags.push(was.available ? 'newly sold out' : 'back in stock')
  if (!was) flags.push('new match')
  console.log(
    `  ${label} ${peso(l.price).padStart(10)}${l.compareAt ? ` (was ${peso(l.compareAt)})` : ''.padEnd(0)}  ${flags.join(', ')}`
  )
}
if (missing.length) console.log(`\nMapped but not found in the store now: ${missing.join(', ')}`)
if (unmapped.length) console.log(`\nNo biolane.ph listing mapped (shown without a price): ${unmapped.join(', ')}`)
if (strayMap.length) console.log(`\nIn shopify-map.ts but not in products.ts: ${strayMap.join(', ')}`)

const header = `// GENERATED by scripts/sync-shopify.mjs on ${fetchedAt} — do not edit by hand.
// The biolane.ph listings the site falls back to when the store can't be
// reached, and the ones the tests run against. Run \`npm run sync-shopify\`
// to refresh it.
import type { CatalogSnapshot } from '../lib/shopify-catalog.ts'

export const shopifySnapshot: CatalogSnapshot = `
writeFileSync(OUT, header + JSON.stringify({ fetchedAt, listings }, null, 2) + '\n')
console.log(`\nWrote data/shopify-snapshot.ts (${Object.keys(listings).length} listings).\n`)
